language: go
go:
  - 1.15.x

addons:
  apt:
    packages:
      - make
    update: true

install:
  - go get github.com/mattn/goveralls

script:
  - make test
  - $GOPATH/bin/goveralls -service=travis-ci
